language: objective-c
osx_image: xcode8.3

branches:
  only:
    - master
env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
script:
  - carthage bootstrap
  - xcodebuild CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
